import { v } from "convex/values";
import type { Doc, Id } from "./_generated/dataModel";
import type { MutationCtx, QueryCtx } from "./_generated/server";
import { mutation, query, assertEventOrganizerAccess } from "./functions";

type Provider = "convex" | "youtube" | "vimeo" | "external";
type Ctx = QueryCtx | MutationCtx;

export function hostedSource(value: string): { url: string; provider: Exclude<Provider, "convex">; embedUrl?: string } {
  let url: URL;
  try { url = new URL(value.trim()); } catch { throw new Error("Enter a valid HTTPS recording URL."); }
  if (url.protocol !== "https:" || url.username || url.password) throw new Error("Hosted recordings must be credential-free HTTPS URLs.");
  const host = url.hostname.toLowerCase().replace(/^www\./, "");
  // Exact-match or require a "." boundary before the suffix — `host.endsWith("youtube.com")`
  // alone also matches a hostile host like "evilyoutube.com", letting an attacker-controlled
  // domain sail through as if it were really youtube.com/vimeo.com.
  const isHost = (candidate: string, suffix: string) => candidate === suffix || candidate.endsWith(`.${suffix}`);
  const youtube = host === "youtu.be" ? url.pathname.slice(1) : isHost(host, "youtube.com") ? url.searchParams.get("v") ?? (url.pathname.match(/^\/(?:embed|shorts)\/([^/]+)/)?.[1]) : undefined;
  if (youtube && /^[\w-]{6,}$/.test(youtube)) return { url: url.toString(), provider: "youtube", embedUrl: `https://www.youtube-nocookie.com/embed/${youtube}` };
  const vimeo = isHost(host, "vimeo.com") ? url.pathname.match(/\/(\d+)(?:\/|$)/)?.[1] : undefined;
  if (vimeo) return { url: url.toString(), provider: "vimeo", embedUrl: `https://player.vimeo.com/video/${vimeo}` };
  return { url: url.toString(), provider: "external" };
}
async function session(ctx: Ctx, eventId: Id<"events">, agendaItemId: Id<"agenda_items">) { const row = await ctx.db.get(agendaItemId); if (!row || row.eventId !== eventId) throw new Error("Session not found for this event."); return row; }
async function activity(ctx: MutationCtx, eventId: Id<"events">, agendaItemId: Id<"agenda_items">, actorUserId: string, action: "attached" | "published" | "published_early" | "unpublished" | "replaced" | "detached" | "migrated", recordingId?: Id<"session_recordings">, detail?: string) { await ctx.db.insert("recording_activity", { eventId, agendaItemId, recordingId, action, detail, actorUserId, createdAt: Date.now() }); }
async function sourceUrl(ctx: QueryCtx, row: Doc<"session_recordings">) { if (row.sourceType === "hosted") return row.hostedUrl; const asset = row.assetId ? await ctx.db.get(row.assetId) : undefined; const storageId = row.storageId ?? asset?.storageId; return storageId ? ctx.storage.getUrl(storageId) : undefined; }
type RecordingSource = { sourceType: "hosted"; hostedUrl: string; provider: Exclude<Provider, "convex"> } | { sourceType: "upload" | "asset"; assetId: Id<"event_assets">; fileName: string; provider: "convex" };
async function attach(ctx: MutationCtx, eventId: Id<"events">, agendaItemId: Id<"agenda_items">, actor: string, source: RecordingSource, legacy = false) {
  const active = await ctx.db.query("session_recordings").withIndex("by_agenda_item_role", q => q.eq("agendaItemId", agendaItemId).eq("role", "active")).first();
  const role = active?.eventId === eventId ? "replacement" as const : "active" as const;
  const candidate = await ctx.db.query("session_recordings").withIndex("by_agenda_item_role", q => q.eq("agendaItemId", agendaItemId).eq("role", role)).first();
  if (candidate?.eventId === eventId && candidate.publicationStatus === "draft") await ctx.db.delete(candidate._id);
  const now = Date.now(); const id = await ctx.db.insert("session_recordings", { eventId, agendaItemId, ...source, role, publicationStatus: "draft", availability: "ready", ...(legacy ? { legacySource: "agenda_video_url" as const } : {}), createdByUserId: actor, createdAt: now, updatedAt: now });
  await activity(ctx, eventId, agendaItemId, actor, legacy ? "migrated" : "attached", id); return id;
}

export const list = query({ args: { eventId: v.id("events"), cursor: v.optional(v.number()), limit: v.optional(v.number()), query: v.optional(v.string()), status: v.optional(v.string()), source: v.optional(v.string()) }, handler: async (ctx, args) => {
  await assertEventOrganizerAccess(ctx, args.eventId);
  const [sessions, rooms, tracks, speakers, recordings] = await Promise.all([ctx.db.query("agenda_items").withIndex("by_event", q => q.eq("eventId", args.eventId)).collect(), ctx.db.query("rooms").withIndex("by_event", q => q.eq("eventId", args.eventId)).collect(), ctx.db.query("tracks").withIndex("by_event", q => q.eq("eventId", args.eventId)).collect(), ctx.db.query("speakers").withIndex("by_event", q => q.eq("eventId", args.eventId)).collect(), ctx.db.query("session_recordings").withIndex("by_event", q => q.eq("eventId", args.eventId)).collect()]);
  const room = new Map(rooms.map(x => [x._id, x.name])), track = new Map(tracks.map(x => [x._id, x.name])), speaker = new Map(speakers.map(x => [x._id, `${x.firstName} ${x.lastName}`.trim()])); const needle = args.query?.trim().toLowerCase();
  const rows = sessions.sort((a,b) => a.startTime-b.startTime).map(item => { const all = recordings.filter(x => x.agendaItemId === item._id); const active = all.find(x => x.role === "active"); const replacement = all.find(x => x.role === "replacement"); return { ...item, roomName: room.get(item.roomId) ?? "Room to be announced", trackName: item.trackId ? track.get(item.trackId) : undefined, speakerNames: item.speakerIds.map(id => speaker.get(id)).filter((value): value is string => Boolean(value)), recording: active ? { id: active._id, sourceType: active.sourceType, fileName: active.fileName, publicationStatus: active.publicationStatus, updatedAt: active.updatedAt, provider: active.provider, availability: active.availability, failureReason: active.failureReason } : undefined, replacement: replacement ? { id: replacement._id, sourceType: replacement.sourceType, fileName: replacement.fileName, updatedAt: replacement.updatedAt, provider: replacement.provider, availability: replacement.availability, failureReason: replacement.failureReason } : undefined }; }).filter(row => !needle || `${row.title} ${row.speakerNames.join(" ")}`.toLowerCase().includes(needle)).filter(row => !args.status ? true : args.status === "missing" ? !row.recording : args.status === "replacement" ? Boolean(row.replacement) : row.recording?.publicationStatus === args.status).filter(row => !args.source || row.recording?.sourceType === args.source);
  const start = args.cursor ?? 0, limit = Math.min(args.limit ?? 500, 500); return rows.slice(start, start + limit);
} });
export const get = query({ args: { eventId: v.id("events"), agendaItemId: v.id("agenda_items") }, handler: async (ctx,args) => { await assertEventOrganizerAccess(ctx,args.eventId); const item=await session(ctx,args.eventId,args.agendaItemId); const rows=(await ctx.db.query("session_recordings").withIndex("by_agenda_item",q=>q.eq("agendaItemId",args.agendaItemId)).collect()).filter(x=>x.eventId===args.eventId); const history=await ctx.db.query("recording_activity").withIndex("by_event_createdAt",q=>q.eq("eventId",args.eventId)).order("desc").take(100); return { session:item, recordings:await Promise.all(rows.map(async row=>({...row,sourceUrl:await sourceUrl(ctx,row),embedUrl:row.sourceType==="hosted"&&row.hostedUrl?hostedSource(row.hostedUrl).embedUrl:undefined}))), history:history.filter(x=>x.agendaItemId===args.agendaItemId) }; } });
export const listAssets = query({ args: { eventId: v.id("events") }, handler: async (ctx, args) => { await assertEventOrganizerAccess(ctx, args.eventId); return ctx.db.query("event_assets").withIndex("by_event", q => q.eq("eventId", args.eventId)).order("desc").take(100); } });
export const attachHosted = mutation({ args:{eventId:v.id("events"),agendaItemId:v.id("agenda_items"),hostedUrl:v.string()}, handler:async(ctx,args)=>{const identity=await assertEventOrganizerAccess(ctx,args.eventId);await session(ctx,args.eventId,args.agendaItemId);const host=hostedSource(args.hostedUrl);return attach(ctx,args.eventId,args.agendaItemId,identity.subject,{sourceType:"hosted" as const,hostedUrl:host.url,provider:host.provider});} });
export const completeUpload = mutation({ args:{eventId:v.id("events"),agendaItemId:v.id("agenda_items"),storageId:v.id("_storage"),fileName:v.string()}, handler:async(ctx,args)=>{const identity=await assertEventOrganizerAccess(ctx,args.eventId);await session(ctx,args.eventId,args.agendaItemId);const meta=await ctx.storage.getMetadata(args.storageId);if(!meta?.contentType?.startsWith("video/"))throw new Error("Upload a supported video file.");if(meta.size>250*1024*1024)throw new Error("Video uploads must be 250 MB or smaller.");const now=Date.now();let asset=await ctx.db.query("event_assets").withIndex("by_storage",q=>q.eq("storageId",args.storageId)).first();if(!asset){const id=await ctx.db.insert("event_assets",{eventId:args.eventId,kind:"video",storageId:args.storageId,fileName:args.fileName.trim().slice(0,255),mimeType:meta.contentType,sizeBytes:meta.size,createdByUserId:identity.subject,createdAt:now,updatedAt:now});asset=await ctx.db.get(id);}if(!asset||asset.eventId!==args.eventId)throw new Error("Upload does not belong to this event.");return attach(ctx,args.eventId,args.agendaItemId,identity.subject,{sourceType:"upload" as const,assetId:asset._id,fileName:asset.fileName,provider:"convex" as const});} });
export const attachUpload = completeUpload;
export const attachAsset = mutation({args:{eventId:v.id("events"),agendaItemId:v.id("agenda_items"),assetId:v.id("event_assets")},handler:async(ctx,args)=>{const identity=await assertEventOrganizerAccess(ctx,args.eventId);await session(ctx,args.eventId,args.agendaItemId);const asset=await ctx.db.get(args.assetId);if(!asset||asset.eventId!==args.eventId)throw new Error("Video asset not found for this event.");return attach(ctx,args.eventId,args.agendaItemId,identity.subject,{sourceType:"asset" as const,assetId:asset._id,fileName:asset.fileName,provider:"convex" as const});}});
async function publishOne(ctx:MutationCtx,eventId:Id<"events">,recordingId:Id<"session_recordings">,actor:string,overrideReason?:string){const row=await ctx.db.get(recordingId);if(!row||row.eventId!==eventId)throw new Error("Recording not found for this event.");const item=await session(ctx,eventId,row.agendaItemId);const early=item.endTime>Date.now();if(early&&!overrideReason?.trim())throw new Error("This session has not ended. Add an override reason to publish early.");if(row.availability!=="ready")throw new Error(row.failureReason ?? "This recording is not ready to publish.");const now=Date.now();if(row.role==="replacement"){const active=await ctx.db.query("session_recordings").withIndex("by_agenda_item_role",q=>q.eq("agendaItemId",row.agendaItemId).eq("role","active")).first();if(active?.eventId===eventId)await ctx.db.patch(active._id,{role:"replaced",publicationStatus:"draft",replacedAt:now,replacedByRecordingId:row._id,publishedAt:undefined,publishedByUserId:undefined,updatedAt:now});await ctx.db.patch(row._id,{role:"active",publicationStatus:"published",publishedAt:now,publishedByUserId:actor,updatedAt:now});await activity(ctx,eventId,row.agendaItemId,actor,"replaced",row._id);if(early)await activity(ctx,eventId,row.agendaItemId,actor,"published_early",row._id,overrideReason?.trim());return row._id;}await ctx.db.patch(row._id,{publicationStatus:"published",publishedAt:now,publishedByUserId:actor,updatedAt:now});await activity(ctx,eventId,row.agendaItemId,actor,early?"published_early":"published",row._id,overrideReason?.trim());return row._id;}
export const publish=mutation({args:{eventId:v.id("events"),recordingId:v.id("session_recordings"),overrideReason:v.optional(v.string())},handler:async(ctx,args)=>publishOne(ctx,args.eventId,args.recordingId,(await assertEventOrganizerAccess(ctx,args.eventId)).subject,args.overrideReason)});
export const unpublish=mutation({args:{eventId:v.id("events"),recordingId:v.id("session_recordings")},handler:async(ctx,args)=>{const actor=(await assertEventOrganizerAccess(ctx,args.eventId)).subject;const row=await ctx.db.get(args.recordingId);if(!row||row.eventId!==args.eventId)throw new Error("Recording not found for this event.");await ctx.db.patch(row._id,{publicationStatus:"draft",publishedAt:undefined,publishedByUserId:undefined,updatedAt:Date.now()});await activity(ctx,args.eventId,row.agendaItemId,actor,"unpublished",row._id);}});
export const detach=mutation({args:{eventId:v.id("events"),recordingId:v.id("session_recordings")},handler:async(ctx,args)=>{const actor=(await assertEventOrganizerAccess(ctx,args.eventId)).subject;const row=await ctx.db.get(args.recordingId);if(!row||row.eventId!==args.eventId)throw new Error("Recording not found for this event.");if(row.publicationStatus==="published")throw new Error("Unpublish this recording before detaching it.");await ctx.db.delete(row._id);await activity(ctx,args.eventId,row.agendaItemId,actor,"detached");}});
export const bulkPublish=mutation({args:{eventId:v.id("events"),recordingIds:v.array(v.id("session_recordings")),overrideReason:v.optional(v.string())},handler:async(ctx,args)=>{const actor=(await assertEventOrganizerAccess(ctx,args.eventId)).subject;const results=[] as Array<{recordingId:Id<"session_recordings">;status:"published"|"failed";error?:string}>;for(const id of [...new Set(args.recordingIds)].slice(0,50)){try{await publishOne(ctx,args.eventId,id,actor,args.overrideReason);results.push({recordingId:id,status:"published"});}catch(error){results.push({recordingId:id,status:"failed",error:error instanceof Error?error.message:"Could not publish."});}}return results;}});
export const bulkUnpublish=mutation({args:{eventId:v.id("events"),recordingIds:v.array(v.id("session_recordings"))},handler:async(ctx,args)=>{const actor=(await assertEventOrganizerAccess(ctx,args.eventId)).subject;const results=[] as Array<{recordingId:Id<"session_recordings">;status:"unpublished"|"failed";error?:string}>;for(const id of [...new Set(args.recordingIds)].slice(0,50)){try{const row=await ctx.db.get(id);if(!row||row.eventId!==args.eventId)throw new Error("Recording not found for this event.");await ctx.db.patch(id,{publicationStatus:"draft",publishedAt:undefined,publishedByUserId:undefined,updatedAt:Date.now()});await activity(ctx,args.eventId,row.agendaItemId,actor,"unpublished",id);results.push({recordingId:id,status:"unpublished"});}catch(error){results.push({recordingId:id,status:"failed",error:error instanceof Error?error.message:"Could not unpublish."});}}return results;}});
export const migrateLegacy=mutation({args:{eventId:v.id("events")},handler:async(ctx,args)=>{const actor=(await assertEventOrganizerAccess(ctx,args.eventId)).subject;const sessions=await ctx.db.query("agenda_items").withIndex("by_event",q=>q.eq("eventId",args.eventId)).collect();let created=0,skipped=0,invalid=0;for(const item of sessions){if(!item.videoUrl)continue;let source;try{source=hostedSource(item.videoUrl);}catch{invalid++;continue;}const exists=(await ctx.db.query("session_recordings").withIndex("by_agenda_item",q=>q.eq("agendaItemId",item._id)).collect()).filter(row=>row.eventId===args.eventId);if(exists.length){skipped++;continue;}await attach(ctx,args.eventId,item._id,actor,{sourceType:"hosted" as const,hostedUrl:source.url,provider:source.provider},true);created++;}return{created,skipped,invalid};}});
