import { useCallback, useEffect, useState } from "react";
import { Plus, Trash2, Users } from "lucide-react";
import { AppLayout } from "@/components/AppLayout";
import { ContentToolbar } from "@/components/shared/ContentToolbar";
import { EmptyState } from "@/components/shared/EmptyState";
import { SkeletonList } from "@/components/shared/SkeletonList";
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle } from "@/components/ui/alert-dialog";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { useRepo } from "@/data/repo";
import type { Organizer } from "@/data/types";

function InviteOrganizer({ onClose, onSaved }: { onClose: () => void; onSaved: () => Promise<void> }) {
  const repo = useRepo(); const [email, setEmail] = useState(""); const [role, setRole] = useState<Organizer["role"]>("admin"); const [busy, setBusy] = useState(false); const [error, setError] = useState<string>();
  const submit = async () => { setBusy(true); setError(undefined); try { await repo.organizers.add({ email, role }); await onSaved(); onClose(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Could not invite team member."); } finally { setBusy(false); } };
  return <div className="space-y-5"><div><h2 className="text-base font-semibold">Invite organization member</h2><p className="mt-1 text-sm text-muted-foreground">Organization roles can access every event. Use an event team for narrower access.</p></div>{error && <p role="alert" className="text-sm text-destructive">{error}</p>}<div className="space-y-2"><Label htmlFor="org-email">Email</Label><Input id="org-email" type="email" value={email} onChange={(e) => setEmail(e.target.value)} autoFocus /></div><div className="space-y-2"><Label>Role</Label><Select value={role} onValueChange={(value) => setRole(value as Organizer["role"])}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="admin">Admin</SelectItem><SelectItem value="owner">Owner</SelectItem></SelectContent></Select></div><div className="flex justify-end gap-2"><Button variant="ghost" onClick={onClose}>Cancel</Button><Button onClick={() => void submit()} disabled={busy || !email.trim()}>{busy ? "Inviting…" : "Invite"}</Button></div></div>;
}

export default function OrganizationSettings() {
  const repo = useRepo(); const [members, setMembers] = useState<Organizer[]>([]); const [mine, setMine] = useState<Organizer | null>(); const [loading, setLoading] = useState(true); const [error, setError] = useState<string>(); const [inviting, setInviting] = useState(false); const [remove, setRemove] = useState<Organizer>();
  const load = useCallback(async () => { setLoading(true); setError(undefined); try { const [rows, current] = await Promise.all([repo.organizers.list(), repo.organizers.getMine()]); setMembers(rows); setMine(current); } catch (cause) { setError(cause instanceof Error ? cause.message : "Could not load organization settings."); } finally { setLoading(false); } }, [repo]);
  useEffect(() => { void load(); }, [load]); const confirmRemove = async () => { if (!remove) return; try { await repo.organizers.remove(remove.userId); setRemove(undefined); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Could not remove team member."); } };
  return <AppLayout title="Organization settings" detail={inviting ? <InviteOrganizer onClose={() => setInviting(false)} onSaved={load} /> : undefined}><div className="space-y-5"><ContentToolbar ariaLabel="Organization team controls" search={<div><h2 className="text-base font-semibold">Team</h2><p className="text-sm text-muted-foreground">People with access to every event workspace.</p></div>} primaryAction={mine?.role === "owner" ? <Button onClick={() => setInviting(true)}><Plus className="mr-2 h-4 w-4" />Invite</Button> : undefined} />{error && <p role="alert" className="text-sm text-destructive">{error}</p>}{loading ? <SkeletonList rows={4} label="Loading organization team…" /> : members.length ? <div className="divide-y divide-muted rounded-lg bg-muted/40">{members.map((member) => <div key={member.id} className="flex items-center gap-4 px-4 py-3"><div className="flex h-9 w-9 items-center justify-center rounded-md bg-background"><Users className="h-4 w-4 text-muted-foreground" /></div><div className="min-w-0 flex-1"><p className="truncate text-sm font-medium">{member.email}</p><p className="text-xs text-muted-foreground">{member.userId.startsWith("pending:") ? "Invitation pending" : "Active"}</p></div><span className="rounded-md bg-background px-2 py-1 text-xs font-medium capitalize">{member.role}</span>{mine?.role === "owner" && member.id !== mine.id && <Button size="icon" variant="ghost" aria-label={`Remove ${member.email}`} onClick={() => setRemove(member)}><Trash2 className="h-4 w-4" /></Button>}</div>)}</div> : <EmptyState message="No organization members yet." />}</div><AlertDialog open={Boolean(remove)} onOpenChange={(open) => { if (!open) setRemove(undefined); }}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Remove organization access?</AlertDialogTitle><AlertDialogDescription>{remove?.email} will lose access to every event unless they also belong to an event team.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Cancel</AlertDialogCancel><AlertDialogAction onClick={() => void confirmRemove()}>Remove access</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog></AppLayout>;
}
